# Generated by Django 4.2 on 2023-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(max_length=20, verbose_name='Precio')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='NombreProducto')),
            ],
        ),
    ]
